# Generated by Django 3.2.10 on 2022-07-20 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trackingPlatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='hash',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='track_code',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 14, 20, 50, 301793, tzinfo=utc)),
        ),
    ]
