# Generated by Django 3.2.10 on 2022-07-21 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trackingPlatform', '0002_auto_20220720_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 12, 35, 35, 544083, tzinfo=utc)),
        ),
    ]
