# Generated by Django 3.2.10 on 2022-07-31 20:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trackingPlatform', '0005_alter_lot_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='state',
            field=models.CharField(default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 20, 49, 50, 831628, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lot',
            name='track_code',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
    ]
